#!/usr/bin/python
import setup
setup.pre_install()

from charmhelpers.core.hookenv import log
from charmhelpers import fetch
from path import path
import subprocess
import logging

pkgs = ['git-core',
        'build-essential',
        'libssl-dev',
        'libsqlite3-dev',
        'openssl',
        'libpq-dev']

here = path(__file__).parent.abspath()
home = path('/home/ubuntu')


logger = logging.getLogger(__name__)


def shell(cmd, boilerplate=". %s/.boilerplate &&" % home):
    cmd = "%s %s" % (boilerplate, cmd)
    log(cmd)
    return subprocess.check_call(cmd, shell=True)


def append_line_once(line, fp):
    if not fp.exists():
        fp.touch()

    if line not in fp.lines():
        fp.write_text(line + '\n', append=True)


def install_ruby_repo(repo, dest):
    cmd = 'git clone %s %s' % (repo, dest)
    if dest.exists():
        with dest:
            shell('git pull --rebase')
    else:
        shell(cmd)

    with dest:
        shell('chown ubuntu:ubuntu -R ./')
        script = here / 'bundle.sh'
        shell('sudo -u ubuntu -s %s' % script, '')


def install(pkgs=pkgs):
    log('Installing cf-webadmin')
    fetch.apt_install(fetch.filter_installed_packages(pkgs))

    if not (home / '.rbenv').exists():
        shell('git clone https://github.com/sstephenson/rbenv.git %s' % (home / '.rbenv'), '')
        shell('git clone https://github.com/sstephenson/ruby-build.git %s/.rbenv/plugins/ruby-build' % home, '')

    boilerplate = home / '.boilerplate'
    append_line_once('export PATH="%s/.rbenv/bin:$PATH"' % home, boilerplate)
    append_line_once('eval "$(rbenv init -)"', boilerplate)

    shell('rbenv install -s 1.9.3-p484')
    shell('rbenv global 1.9.3-p484')

    shell('gem install bundler --no-rdoc --no-ri')
    shell('rbenv rehash')

    opt = path('/opt').mkdir_p()

    install_ruby_repo('https://github.com/cloudfoundry-incubator/admin-ui.git', opt / 'admin-ui')
    install_ruby_repo('https://github.com/cloudfoundry/cf-uaac.git', opt / 'uaac')



if __name__ == "__main__":
    install()
