#!/usr/bin/python
import setup
setup.pre_install()

from charmhelpers.core.hookenv import log
from charmhelpers import fetch
from path import path
from utils import home
from utils import shell

import logging

pkgs = ['git-core',
        'build-essential',
        'libssl-dev',
        'libsqlite3-dev',
        'openssl',
        'libpq-dev',
        'libmysqlclient-dev']

here = path(__file__).parent.abspath()

logger = logging.getLogger(__name__)


def install_ruby_repo(repo, dest):
    cmd = 'git clone %s %s' % (repo, dest)
    if dest.exists():
        with dest:
            shell('git pull --rebase')
    else:
        shell(cmd)

    with dest:
        shell('chown ubuntu:ubuntu -R ./')
        script = here / 'bundle.sh'
        shell('sudo -u ubuntu -s %s' % script, '')


def install(pkgs=pkgs):
    log('Installing cf-webadmin')
    fetch.apt_install(fetch.filter_installed_packages(pkgs))

    if not (home / '.rbenv').exists():
        rc = 'git clone https://github.com/sstephenson/rbenv.git %s' % (home / '.rbenv')
        shell(rc, '')
        rp = 'git clone https://github.com/sstephenson/ruby-build.git %s/.rbenv/plugins/ruby-build' % home
        shell(rp, '')

    boilerplate = home / '.boilerplate'
    bp_txt = "\n".join(('export PATH="/opt/uaac/bin:%s/.rbenv/bin:$PATH"' % home,
                        'eval "$(rbenv init -)"'))

    boilerplate.write_text(bp_txt)

    shell('rbenv install -s 1.9.3-p484')
    shell('rbenv global 1.9.3-p484')

    shell('gem install bundler --no-rdoc --no-ri')
    shell('gem install mysql2 --no-rdoc --no-ri')
    shell('rbenv rehash')

    opt = path('/opt').mkdir_p()

    install_ruby_repo('https://github.com/cloudfoundry-incubator/admin-ui.git',
                      opt / 'admin-ui')

    install_ruby_repo('https://github.com/cloudfoundry/cf-uaac.git',
                      opt / 'uaac')


if __name__ == "__main__":
    install()
