#!/usr/bin/python
import setup
setup.pre_install()

from charmhelpers import fetch
from charmhelpers.core.hookenv import config
from charmhelpers.core.hookenv import log
from path import path
from utils import shell

pkgs = ['git-core',
        'build-essential',
        'libssl-dev',
        'libsqlite3-dev',
        'openssl',
        'libpq-dev',
        'libmysqlclient-dev',
        'ruby1.9.3',
        'bundler']

here = path(__file__).parent.abspath()
charm = here.parent

templates = charm / 'templates'
uaac_repo = 'https://github.com/cloudfoundry/cf-uaac.git'


def install_ruby_repo(repo, dest, overwrites=None):
    cmd = 'git clone %s %s' % (repo, dest)
    if dest.exists():
        with dest:
            shell('git pull --rebase')
    else:
        shell(cmd)

    if not overwrites is None:
        for fp in overwrites:
            fp.copy(dest / fp.basename())

    with dest:
        shell('chown ubuntu:ubuntu -R ./')
        shell('sudo -u ubuntu -s bundle install')


def install(pkgs=pkgs):
    log('Installing cf-webadmin')
    fetch.apt_install(fetch.filter_installed_packages(pkgs))

    shell('gem install bundler --no-rdoc --no-ri')
    shell('gem install mysql2 --no-rdoc --no-ri')

    opt = path('/opt').mkdir_p()

    cfg = config()
    install_ruby_repo(cfg['repository'],
                      opt / 'admin-ui', (templates / 'Gemfile.lock', ))

    install_ruby_repo(uaac_repo, opt / 'uaac')


if __name__ == "__main__":
    install()
